"""add departments + soldier.department_id

Revision ID: 4fc8a180346b
Revises: 2e0df8126ca0
Create Date: 2025-10-10 12:34:26.114248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc8a180346b'
down_revision: Union[str, None] = '2e0df8126ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
