"""add vacations

Revision ID: 66fffa2f349e
Revises: 486543202fe4
Create Date: 2025-10-08 08:53:34.428801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fffa2f349e'
down_revision: Union[str, None] = '486543202fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soldier_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['soldier_id'], ['soldiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vacations_soldier_range', 'vacations', ['soldier_id', 'start_date', 'end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacations_soldier_range', table_name='vacations')
    op.drop_table('vacations')
    # ### end Alembic commands ###
