"""multi roles: soldier_roles + code updates

Revision ID: 86458f984bfd
Revises: 4fc8a180346b
Create Date: 2025-10-10 12:57:26.027510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86458f984bfd'
down_revision: Union[str, None] = '4fc8a180346b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soldier_roles',
    sa.Column('soldier_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['soldier_id'], ['soldiers.id'], ),
    sa.PrimaryKeyConstraint('soldier_id', 'role_id'),
    sa.UniqueConstraint('soldier_id', 'role_id', name='uq_soldier_role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soldier_roles')
    # ### end Alembic commands ###
