"""add unique+index for assignments window

Revision ID: dc5ef460adb8
Revises: 66fffa2f349e
Create Date: 2025-10-09 08:03:36.693906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5ef460adb8'
down_revision: Union[str, None] = '66fffa2f349e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_assignments_soldier_time', 'assignments', ['soldier_id', 'start_at', 'end_at'], unique=False)
    op.create_unique_constraint('uq_assignments_soldier_window', 'assignments', ['soldier_id', 'start_at', 'end_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_assignments_soldier_window', 'assignments', type_='unique')
    op.drop_index('ix_assignments_soldier_time', table_name='assignments')
    # ### end Alembic commands ###
